plugins {
    id 'java'

}

group = 'com.nutritiondaily'
version = '0.0.1-SNAPSHOT'
description = 'nutrition-daily'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {

}

tasks.named('test') {
    useJUnitPlatform()
}